Resolve merge conflict for app sidecar.
Currently master-asm and release-1.23-asm builds are failing with errors
similar to bellow.
ERROR: target app_sidecar_rockylinux_9-debug: failed to solve: gcr.io/asm-staging-images/app_sidecar_base_rockylinux_9:release-1.23-asm-2024-09-19T14-08-23

Change-Id: I7c224295ccface618aee850bad387b6da0241079
Reviewed-on: https://gke-internal-review.googlesource.com/c/istio/istio/+/1152400
MDP-Verified: Prow_Bot_V2 <425329972751-compute@developer.gserviceaccount.com>
Tested-by: Prow_Bot_V2 <425329972751-compute@developer.gserviceaccount.com>
Reviewed-by: Hemendra Teli <hemendrat@google.com>
CloudESF-Verified: Prow_Bot_V2 <425329972751-compute@developer.gserviceaccount.com>
Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Prow-Auto-Submit: Sergii Shapar <sshapar@google.com>