MDP patches
controller-runtime has been upgraded to v1.19.0 and workqueue types and functions have been deprected.

Fixes
```
mdp/controller/pkg/revision/pod.go:67:9: cannot use &podEventHandler{…} (value of type *podEventHandler) as handler.TypedEventHandler["sigs.k8s.io/controller-runtime/pkg/client".Object, reconcile.Request] value in return statement: *podEventHandler does not implement handler.TypedEventHandler["sigs.k8s.io/controller-runtime/pkg/client".Object, reconcile.Request] (wrong type for method Create)
		have Create(context.Context, event.TypedCreateEvent["sigs.k8s.io/controller-runtime/pkg/client".Object], workqueue.RateLimitingInterface)
		want Create(context.Context, event.TypedCreateEvent["sigs.k8s.io/controller-runtime/pkg/client".Object], workqueue.TypedRateLimitingInterface[reconcile.Request])
```

Change-Id: I4f4f0a43c346d033b702706def5a1f7f9878c220
Reviewed-on: https://gke-internal-review.googlesource.com/c/istio/istio/+/1132077
Tested-by: Sergii Shapar <sshapar@google.com>
Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Reviewed-by: Hemendra Teli <hemendrat@google.com>
CloudESF-Verified: Sergii Shapar <sshapar@google.com>
MDP-Verified: Sergii Shapar <sshapar@google.com>